openapi: 3.0.0
info:
  version: 1.2.0
  title: Destiny API -- Info
servers:
  - url: '/destiny/context/{context}/rest/'
    variables: 
      context: 
        default: 'destiny'
        description: 'Context of the destiny district'
paths:
  '/api/versioninfo':
    get:
      summary: 'Get information about Destiny API deployments'
      description: >-
        Get general version information about the Destiny Open API.
        Does not require any specific permissions.
      operationId: getVersionInfo
      tags:
        - Version Info
      responses:
        '200':
          description: >-
            Information about the deployed APIs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
              example:
                destinyVersion: "17.5.0.0"
                apiHighestMajorVersion: 2
                apiDeployments:
                  - name: "Destiny API Version 1"
                    majorVersion: 1
                    minorVersion: 3
                    patchVersion: 1
                    fullVersion: "1.3.1"
                    endOfLifeDate: "2020-06-10"
                    uri: "https://florida.state.edu/api/v1/rest/context/miami"
                  - name: "Destiny API Version 2"
                    majorVersion: 2
                    minorVersion: 0
                    patchVersion: 1
                    fullVersion: "2.0.1"
                    endOfLifeDate: "2020-06-10"
                    uri: "https://florida.state.edu/api/v2/rest/context/miami"
        '500':
          description: This is an unexpected fault/error in the server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: BaseException
                message: Something bad happened in the server
                logId: kxEtz
components:
  schemas:
    VersionInfo:
      properties:
        destinyVersion:
          type: string
          description: 'Version of the Destiny server'
        apiHighestMajorVersion:
          type: integer
          description: 'Highest major version of the API deployed'
        apiDeployments:
          type: array
          items: 
            type: object
            properties:
              name:
                type: string
                description: 'the name of the API deployment'
              majorVersion:
                type: integer
                description: 'the major version'
              minorVersion:
                type: integer
                description: 'the minor version'
              patchVersion:
                type: integer
                description: 'the patch level'
              fullVersion:
                type: string
                description: 'the full version name'
              endOfLifeDate:
                type: string
                description: 'the ISO-8601 formatted date after which we expect this API version to no longer be deployed'
              rootUrl:
                type: string
                description: 'the root path where the API is deployed'
    Error:
      required:
        - code
        - message
      properties:
        error: 
          type: object
          properties:           
            code:
              type: string
              description: 'Identifies the type of errors that could happen when calling this API.'
              enum: 
                - CODE_CONTEXT_NOT_FOUND
                - CODE_CONTEXT_REQUIRED_IN_CONSORTIUM
            message:
              type: string
              description: 'A human readable message about the error.'
            target:
              type: string
              description: 'Field, parameter or path associated with the error'
            logId:
              type: string
              description: 'A unique value generated and written to the Destiny log file in association with the error.'
